// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "getting-started/design-principles.mdx": () => import("../content/docs/getting-started/design-principles.mdx?collection=docs"), "getting-started/index.mdx": () => import("../content/docs/getting-started/index.mdx?collection=docs"), "implementation/blockchain-integration.mdx": () => import("../content/docs/implementation/blockchain-integration.mdx?collection=docs"), "implementation/cryptography.mdx": () => import("../content/docs/implementation/cryptography.mdx?collection=docs"), "implementation/error-handling.mdx": () => import("../content/docs/implementation/error-handling.mdx?collection=docs"), "implementation/index.mdx": () => import("../content/docs/implementation/index.mdx?collection=docs"), "core-protocol/data-transfer.mdx": () => import("../content/docs/core-protocol/data-transfer.mdx?collection=docs"), "core-protocol/handshake.mdx": () => import("../content/docs/core-protocol/handshake.mdx?collection=docs"), "core-protocol/index.mdx": () => import("../content/docs/core-protocol/index.mdx?collection=docs"), "core-protocol/payment-channels.mdx": () => import("../content/docs/core-protocol/payment-channels.mdx?collection=docs"), "core-protocol/verification.mdx": () => import("../content/docs/core-protocol/verification.mdx?collection=docs"), "reference/future-extensions.mdx": () => import("../content/docs/reference/future-extensions.mdx?collection=docs"), "reference/message-types.mdx": () => import("../content/docs/reference/message-types.mdx?collection=docs"), "reference/references.mdx": () => import("../content/docs/reference/references.mdx?collection=docs"), "security/economic-attacks.mdx": () => import("../content/docs/security/economic-attacks.mdx?collection=docs"), "security/index.mdx": () => import("../content/docs/security/index.mdx?collection=docs"), "security/payment-verification.mdx": () => import("../content/docs/security/payment-verification.mdx?collection=docs"), "security/privacy.mdx": () => import("../content/docs/security/privacy.mdx?collection=docs"), }),
};
export default browserCollections;